# https://docs.github.com/en/actions/tutorials/publish-packages/publish-nodejs-packages
name: Continuous Deployment

on:
  release:
    types: [published]

jobs:
  publish:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-24.04

    permissions:
      contents: 'read'
      packages: 'write'

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v7

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v7
        with:
          node-version-file: 'package.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ihori-system'

      - run: npm ci

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
